### ISSUE TITLE
Want to use this on TViOS, but unable to do so? Can you rebuild for this architecture?

### ISSUE THREAD

**Issue by wizard1066** [marmelroy/Zip#12]
Want to use this on TViOS, but unable to do so? Can you rebuild for this architecture?

**Comment by marmelroy** [comment]
Sure @wizard1066 ... I'll do it this evening.

**Comment by marmelroy** [comment]
tvOS target added.

**Comment by wizard1066** [comment]
Tried to update with this command? But it didn't work? I am missing something here, sorry new to carthage.

carthage update --platform tvOS
*** Fetching Zip
*** Checking out Zip at "0.4.0"
*** xcodebuild output can be found in /var/folders/rd/m94y05zs6836d9lrmh44f0b40000gp/T/carthage-xcodebuild.oWrDOw.log
*** Skipped building Zip due to the error:
Dependency "Zip" has no shared framework schemes for any of the platforms: tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/marmelroy/Zip/issues/new

**Comment by marmelroy** [comment]
Ah yes... sorry... fixing.

**Comment by marmelroy** [comment]
Should be fixed with release 0.4.1. The target scheme was not marked as 'shared'.

**Comment by wizard1066** [comment]
Sorry, Still not working it seems?

carthage update --platform tvOS
*** Fetching Zip
*** Checking out Zip at "0.4.1"
*** xcodebuild output can be found in /var/folders/rd/m94y05zs6836d9lrmh44f0b40000gp/T/carthage-xcodebuild.XfIsSN.log
*** Building scheme "Zip tvOS" in Zip.xcodeproj
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, id:70D37FB7-300A-46EA-8493-27489B757341 }
A shell task (/usr/bin/xcrun xcodebuild -project /Users/localuser//SwiftCode/Carthage/Checkouts/Zip/Zip.xcodeproj -scheme Zip tvOS -configuration Release -sdk appletvsimulator -destination platform=tvOS Simulator,id=70D37FB7-300A-46EA-8493-27489B757341 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 70:
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, id:70D37FB7-300A-46EA-8493-27489B757341 }

**Comment by marmelroy** [comment]
Sorry... we'll get there eventually... 😄 fix soon...

**Comment by marmelroy** [comment]
Now it's really fixed (checked with carthage update --platform tvOS). Sorry for the mistakes along the way...

**Comment by wizard1066** [comment]
Hi Roy,
Thanks for your perseverance on this ... sadly we're not quite there it seems... perhaps I made another mistake. I now see.

/Users/localuser/Dropbox/SwiftCode/ATVblueServer/ATVblueServer/ViewController.swift:17:8: Module file was created for incompatible target arm64-apple-ios8.0: /Users/localuser/SwiftCode/Carthage/Build/iOS/Zip.framework/Modules/Zip.swiftmodule/arm64.swiftmodule

**Comment by marmelroy** [comment]
Looks like it's picking the wrong framework (the iOS one). For me the folder is Carthage/Build/tvOS/Zip.framework/Modules/... 

I'll try and replicate...

**Comment by wizard1066** [comment]
I Roy, Just tried 4.2. Sadly same error message; doesn't link... wrong dynamic libraries it seems.

**Comment by marmelroy** [comment]
Carthage support was dropped with the latest release.
