### ISSUE TITLE
No Mac platform support

### ISSUE THREAD

**Issue by lauritzsh** [marmelroy/Zip#6]
Hi, I am using Carthage and I unfortunately see no `Zip.framework` for Mac. I am curious if this is intentional or why there is no scheme for OS X. Would be really useful. Thanks.

```
*** Skipped building Zip due to the error:
Dependency "Zip" has no shared framework schemes for any of the platforms: Mac

If you believe this to be an error, please file an issue with the maintainers at https://github.com/marmelroy/Zip/issues/new
```

**Comment by tbaranes** [comment]
+1

**Comment by marmelroy** [comment]
Good idea. On it.

**Comment by marmelroy** [comment]
Solved by https://github.com/marmelroy/Zip/commit/9048a8856029ddbbb1774ac55873956084e4fa5f

**Comment by lauritzsh** [comment]
Thank you! :+1:

**Comment by lauritzsh** [comment]
Hi, I am unfortunately still getting

```
$ carthage update --platform mac
*** Fetching Zip
*** Fetching Alamofire
*** Checking out Alamofire at "3.2.1"
*** Checking out Zip at "0.3.1"
*** xcodebuild output can be found in /var/folders/9_/mvq9n5cx1j90mk4h1q_1gky80000gn/T/carthage-xcodebuild.nKlQrh.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Skipped building Zip due to the error:
Dependency "Zip" has no shared framework schemes for any of the platforms: Mac

If you believe this to be an error, please file an issue with the maintainers at https://github.com/marmelroy/Zip/issues/new
```

I have tried `bootstrap` as well. Am I doing anything wrong with Carthage? Tried removing the entire `Carthage` folder with its `Build` and `Checkout` directories.

My `Cartfile` is pretty simple and should be using newest version

```
$ cat Cartfile
github "Alamofire/Alamofire" ~> 3.2.1
github "marmelroy/Zip" ~> 0.3

$ cat Cartfile.resolved
github "Alamofire/Alamofire" "3.2.1"
github "marmelroy/Zip" "0.3.1"
```

Thanks!

**Comment by marmelroy** [comment]
That's my fault. I forgot Carthage needs the osx target to be 'shared'. Should be fixed with 0.3.2.
